apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    project: devops-mysql-data
  name: devops-mysql-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
